### ISSUE TITLE
test smr api

### ISSUE THREAD

**Issue by awaterho** [CATH-SWISSMODEL/cath-swissmodel-api#7]
Hi Ian, 

I hand made an OpenAPI specification for the SWISS-MODEL repository. Is that even the correct terminology? Its not the API, thats written in code, so is OpenAPI specification the correct term for the JSON file I created?

Do people provide both YAML and JSON? 

You might like to try it out here, its a very temporary location which can be deleted at any moment:
https://swissmodel.expasy.org/static/dist/smr_openapi.html

I will continue to work with DjangoRestAPI which is the Python framework which will be using to on our server. I'll see how it creates the API specification automatically.

**Comment by sillitoe** [comment]
Nice!

> Is that even the correct terminology?  ... is OpenAPI specification the correct term for the JSON file I created?

Yup, all sounds good to me.

I guess ultimately we would want this document to be automatically generated by the DjangoRestAPI - looks like that will involve using one of the following:

http://www.django-rest-framework.org/topics/documenting-your-api

Probably worth using this to generate a static version of the OpenAPI spec as part of the build / release? Think it makes sense for a static version of this document to be in version control.

> Do people provide both YAML and JSON?

If you are generating code from the spec document then probably not (you wouldn't want to maintain more than one file by hand). If you are generating the spec document from code then I guess it doesn't add any effort to make both YAML and JSON versions available. It would definitely be good to pick one of those document generators that can produce both v2.0 and v3.0 compatible documents.

Great - DjangoRestAPI looks good. I'll look into implementing ours in this too.

**Comment by sillitoe** [comment]
Closing this ticket as we have a beta SM server and we've implemented a build with (passing) tests.
